apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/service.yaml
- manifests/deployment.yaml
- manifests/deployment_todo.yaml
- manifests/service_todo.yaml
- manifests/statefulset.yaml

images:
- name: PROJECT/IMAGE
  newName: ahamzahhh/project
  newTag: 0835c68e22b654909df2e2182924d6a693cec2a4
