apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-claim # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: local-path # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: project-claim
      containers:
        - name: project-dep
          image: PROJECT/IMAGE
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/cache
          env:
           - name: PORT
             value: "3003"
           - name: BACKEND_URL
             value: "http://34.88.206.48/todos"

        