apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dwk-material-ingress
  namespace: project
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: project-svc
            port:
              name: frontend
      - path: /todos # Example path for the backend API (optional)
        pathType: Prefix
        backend:
          service:
            name: project-svc
            port:
              name: backend  # Backend service on port 4000