apiVersion: v1
kind: Service
metadata:
  name: project-svc
spec:
  type: LoadBalancer
  selector:
    app: project # This matches the label in the pod template
  ports:
    - port: 80  # Port for the frontend
      targetPort: 3003  # This is the port inside the container (frontend)
      protocol: TCP