name: Delete Environment

on:
  delete:
    branches: # Triggered when a branch is deleted
      - '**'

jobs:
  delete-environment:
    name: Delete Kubernetes Environment
    runs-on: ubuntu-latest
    environment: sirit # Specify the environment

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Delete Kubernetes Namespace
        run: |
          kubectl delete namespace ${BRANCH} || echo "Namespace ${BRANCH} not found."
